Fix query string truncation while dispatching to QE
Execution of a long enough query containing multi-byte characters can
cause incorrect truncation of the query string. Incorrect truncation
implies an occasional cut of a multi-byte character and (with
log_min_duration_statement set to 0 ) subsequent write of an invalid
symbol to segment logs. Such broken character present in logs produces
problems when trying to fetch logs info from
gp_toolkit.__gp_log_segment_ext  table - queries fail with the following
error: «ERROR: invalid byte sequence for encoding…».
This is caused by buildGpQueryString function in `cdbdisp_query.c`,
which prepares query text for dispatch to QE. It does not take into
account character length when truncation is necessary (text is longer
than QUERY_STRING_TRUNCATE_SIZE).

Cherry picked from 889ba39 and ef09a3a