Fix minirepro/gpsd os.getlogin() issue
https://bugs.python.org/issue584566

On CI machines `os.getlogin()` failed with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  OSError: [Errno 6] No such device or address
```

Changes to the original commit:
In gpsd utility we do not support using environmental variables for getting
values of parameters, so we don't need `'PGUSER' in envOpts`.

Co-authored-by: Soumyadeep Chakraborty <sochakraborty@pivotal.io>
(cherry picked from commit 241672bb758774b29af7c791b8615526551edccf)