Revert gpstart gpsubprocess update (#414)
In 37ab4e12ccb793b0f2e0acc2d04589c3613a02da we updated a lot of modules,
replacing subprocess with gpsubprocess. But the gpsubprocess module in case of
python2 relies on subprocess32 package for managing subprocesses, which is
pretty-much outdated itself (in our project).

So when we try to combine this subprocesses32 module and coverage utility via
hooking it with site-module, we get following error: 

File "test/behave/mgmt_utils/steps/gpstart.py", line 89, in impl
     preexec_fn=_handle_sigpipe,
RuntimeError: not holding the import lock

To solve this we should revert changes on gpstart.py from mentioned previously
patch, as updating gpsubprocess will also solve the problem, but on the other
hand will bring even more errors.