Fix tautological undefined compare
The compiler is right, 'this' is defined to be never null. We fixed
something like this in commit b111104f820ab53e but this recently slipped
through the cracks.

Example error message (varies between versions and compilers):

> libnaucrates/src/statistics/CBucket.cpp:453:14: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]

(cherry picked from commit a4274d938f49e1ace083b50feaec23e0d61955e9)