Handle missing system attributes for AO table correctly (#671)
AO tables by nature do not have special system columns like xmin, xmax, cmin,
cmax. When querying AO tables, the absence of a system attribute is detected
only during processing a tuple and an error is generated similar to this one:

ERROR: Invalid attnum: -3

This message can confuse some users.

This patch adds check at semantic analysis stage and give more meaningful
message to the user:

ERROR: AO-table has no "xmin" column

Co-authored-by: Georgy Shelkovy g.shelkovy@arenadata.io