Don't report compress option errors if not validating
```
adam=# CREATE TABLE ao_reloptions_t1 (c1 INT) WITH (appendonly=true, compresstype=zstd);
CREATE TABLE
adam=# SET allow_system_table_mods = on;
SET
adam=# UPDATE pg_class SET reloptions = '{compresstype=zzzz}' WHERE relname = 'ao_reloptions_t1';
UPDATE 1
adam=# DROP TABLE ao_reloptions_t1;
ERROR:  unknown compresstype "zzzz"

adam=# CREATE TABLE ao_reloptions_t2 (c1 INT) WITH (appendonly=true, compresstype=zstd);
CREATE TABLE
adam=# UPDATE pg_class SET reloptions = '{appendonly=true,compresstype=quicklz,compresslevel=3}' WHERE relname = 'ao_reloptions_t2';
UPDATE 1
adam=# DROP TABLE ao_reloptions_t2;
ERROR:  QuickLZ library is not supported by this build
HINT:  Compile with --with-quicklz to use QuickLZ compression.
```

`validate_and_adjust_options()` doesn't respect the bool parameter
`validate` in some cases. This commit fixes it.

(cherry picked from commit d8f394be232e44793e0dc44adbd7e0ff49b5c910)

Changes compared to the original commit:
- add check for compression type before loading shared library